import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="w-full px-4 bg-white md:px-8 lg:px-16 xl:px-32">
            <Navbar />
          </div>
          <div className=" px-4 bg-slate-100 md:px-8 lg:px-16 xl:px-32">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
